Sandstorm:
  GedmoTranslatableConnector:
    locale: mul_ZZ
    defaultLocale: mul_ZZ

Neos:
  Flow:
    # disable reflection for non psr-0 compliant 3rd party packages
    object:
      excludeClasses:
       'gedmo.doctrineextensions' : ['Gedmo\\.*']

    # Register the "Translatable" listener as Doctrine Event listener
    persistence:
      doctrine:
        eventListeners:
          'Gedmo\Translatable\TranslatableListener':
            events: ['postLoad', 'postPersist', 'preFlush', 'onFlush', 'loadClassMetadata']
            listener: 'Gedmo\Translatable\TranslatableListener'
